# The numpy.random package

## Overall purpose of the numpy.random package 

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.[1]

Numpy random 



## Simple Random Data using the numPY package:

In [2]:
# Efficient numerical arrays.
import numpy as np
from numpy import random

# Plotting.
import matplotlib.pyplot as plt


### Practice from the new Numpy Documentation[2]

https://numpy.org/doc/1.21/

In [4]:
rng = np.random.default_rng()

[1](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [5]:
#rng.intergers(2, size =10)
#NameError                                 Traceback (most recent call last)
#<ipython-input-2-6ab1ec57f0ad> in <module>
#----> 1 rng.intergers(2, size =10)
#AttributeError: 'numpy.random._generator.Generator' object has no attribute 'intergers'

# choice is the new name for the intergers
rng.choice(2, size=20)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [12]:
rng.random()

0.1469191970481778

In [13]:
type(rng.random())

float

In [14]:
rng.random((5,))

array([0.97139477, 0.53838074, 0.3020164 , 0.13945874, 0.98732938])

In [15]:
5 * rng.random((3, 2)) - 5
#Three-by-two array of random numbers from [-5, 0):

array([[-2.35039064, -2.82494238],
       [-0.30480223, -3.48580857],
       [-0.02172729, -3.58877727]])

In [16]:
rng.choice(5, 3)
##This is equivalent to rng.integers(0,5,3)
#Generate a uniform random sample from np.arange(5) of size 3:

array([0, 2, 3], dtype=int64)

In [17]:
#Generate a non-uniform random sample from np.arange(5) of size 3:
rng.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])


array([3, 3, 0], dtype=int64)

In [18]:
#Generate a uniform random sample from np.arange(5) of size 3 without replacement:
rng.choice(5, 3, replace=False)
#This is equivalent to rng.permutation(np.arange(5))[:3]

array([1, 0, 3], dtype=int64)

In [19]:
#Generate a uniform random sample from a 2-D array along the first axis (the default), without replacement:
rng.choice([[0, 1, 2], [3, 4, 5], [6, 7, 8]], 2, replace=False)

array([[6, 7, 8],
       [0, 1, 2]])

In [20]:
names= ['pooh', 'rabbit', 'piglet', 'Peppa']
rng.choice(names, 5, p=[0.5, 0.1, 0.1, 0.3])


array(['rabbit', 'pooh', 'Peppa', 'Peppa', 'pooh'], dtype='<U6')

In [3]:
np.random.rand(3,2)


array([[0.7401139 , 0.21828967],
       [0.54322138, 0.19928235],
       [0.25555157, 0.38387184]])

In [4]:
np.random.randn()

-2.8780051447492925

In [5]:
#Two-by-four array of samples from N(3, 6.25):
3 + 2.5 * np.random.randn(2, 4)

array([[3.17354548, 5.86119691, 5.55100204, 5.80847782],
       [8.76552096, 3.3826997 , 3.81767511, 5.40494446]])

In [8]:
np.random.randint(5)
#https://numpy.org/doc/1.21/reference/random/generated/numpy.random.RandomState.random_integers.html

2

In [9]:
np.random.randint(5, size=(3,2))

array([[0, 4],
       [0, 4],
       [1, 4]])

### References:
[1](https://numpy.org/devdocs/user/whatisnumpy.html)
[2](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html)
